# Generated by Django 5.0.1 on 2024-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='lol', max_length=128),
            preserve_default=False,
        ),
    ]
