# Generated by Django 5.0.1 on 2024-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
