# Generated by Django 4.2.5 on 2023-10-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprofile',
            name='contact_email',
        ),
    ]
