# Generated by Django 4.2.5 on 2023-10-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_remove_oprofile_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Logo'),
        ),
    ]
