# Generated by Django 5.0 on 2023-12-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_alter_oprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_time', models.TimeField()),
                ('registration_deadline', models.DateField()),
                ('registered', models.IntegerField(default=0)),
                ('total_volunteers_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('included_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('included_description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.event')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('requirement_description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.event')),
            ],
        ),
    ]
