# Generated by Django 5.0 on 2023-12-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_event_includeditem_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/', verbose_name='banner'),
        ),
    ]
