# Generated by Django 5.0.2 on 2024-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_skills_created_at_skills_last_modefied'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='Category',
            field=models.CharField(default='lol', max_length=100, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
